# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_mgt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='carrier',
        ),
        migrations.AddField(
            model_name='flight',
            name='carrier_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='carrier', to='flight_mgt.Carrier'),
        ),
    ]
