# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_mgt', '0002_auto_20180702_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightbooking',
            name='eta',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='etd',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='user',
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='carrier_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='flight_carrier', to='flight_mgt.Carrier'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='flight_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='flight_mgt.Flight'),
        ),
    ]
