# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_mgt', '0003_auto_20180703_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='carrier_id',
            new_name='carrier',
        ),
        migrations.RenameField(
            model_name='flightbooking',
            old_name='carrier_id',
            new_name='carrier',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='flight_id',
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='flight',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='flight_mgt.Flight'),
        ),
    ]
